package Analizadores;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 49;
  public static final int In = 16;
  public static final int Comma = 23;
  public static final int True = 59;
  public static final int Aparecium = 10;
  public static final int Differentto = 55;
  public static final int Examino = 9;
  public static final int If = 14;
  public static final int Id = 30;
  public static final int Equal = 56;
  public static final int Typeint = 28;
  public static final int Opencurl = 17;
  public static final int Else = 15;
  public static final int Reditus = 11;
  public static final int Pow = 43;
  public static final int Typestring = 29;
  public static final int Semicolon = 24;
  public static final int Str = 2;
  public static final int Lessequal = 51;
  public static final int Colon = 25;
  public static final int Typefloat = 33;
  public static final int Alohomora = 3;
  public static final int Geminio = 6;
  public static final int Typeboolean = 36;
  public static final int Int = 32;
  public static final int Float = 58;
  public static final int Finite = 8;
  public static final int Closeparent = 22;
  public static final int Andperseand = 46;
  public static final int EOF = 0;
  public static final int And = 48;
  public static final int Not = 47;
  public static final int Typeebublio = 37;
  public static final int error = 1;
  public static final int Openparent = 21;
  public static final int Focus = 5;
  public static final int False = 60;
  public static final int Autominus = 39;
  public static final int Greater = 52;
  public static final int InvalidToken = 61;
  public static final int Mult = 42;
  public static final int Char = 57;
  public static final int Div = 44;
  public static final int Typedouble = 34;
  public static final int Dot = 26;
  public static final int Closecurl = 18;
  public static final int Less = 53;
  public static final int Equalto = 54;
  public static final int Typechar = 27;
  public static final int Mod = 45;
  public static final int Closebracket = 20;
  public static final int Saltus = 13;
  public static final int NewLine = 31;
  public static final int Typepointer = 35;
  public static final int Avadakedavra = 12;
  public static final int Minus = 41;
  public static final int Giratiempo = 7;
  public static final int Greaterequal = 50;
  public static final int Plus = 40;
  public static final int Autoplus = 38;
  public static final int Aberto = 4;
  public static final int Openbracket = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Str",
  "Alohomora",
  "Aberto",
  "Focus",
  "Geminio",
  "Giratiempo",
  "Finite",
  "Examino",
  "Aparecium",
  "Reditus",
  "Avadakedavra",
  "Saltus",
  "If",
  "Else",
  "In",
  "Opencurl",
  "Closecurl",
  "Openbracket",
  "Closebracket",
  "Openparent",
  "Closeparent",
  "Comma",
  "Semicolon",
  "Colon",
  "Dot",
  "Typechar",
  "Typeint",
  "Typestring",
  "Id",
  "NewLine",
  "Int",
  "Typefloat",
  "Typedouble",
  "Typepointer",
  "Typeboolean",
  "Typeebublio",
  "Autoplus",
  "Autominus",
  "Plus",
  "Minus",
  "Mult",
  "Pow",
  "Div",
  "Mod",
  "Andperseand",
  "Not",
  "And",
  "Or",
  "Greaterequal",
  "Lessequal",
  "Greater",
  "Less",
  "Equalto",
  "Differentto",
  "Equal",
  "Char",
  "Float",
  "True",
  "False",
  "InvalidToken"
  };
}

